#!/bin/bash

IMG=iiab-6.4-171118-medbox-beta2-32G-g3ea4256.img

echo $IMG

ia upload $IMG $IMG.zip --metadata="mediatype:software" --metadata="collection:internetinabox" \
 --metadata="title:Medical Internet in a Box Beta 2 (32G)" \
 --metadata="language:eng" \
 --metadata="description:Medical Internet in a Box Beta for Raspberry Pi<BR>Release: $IMG" \
 --metadata="creator:Internet in a Box" \
 --metadata="subject:rpi"  \
 --metadata="subject:wikipedia" \
 --metadata="subject:medical" \
 --metadata="licenseurl:http://creativecommons.org/licenses/by-sa/4.0/"

