#!/bin/bash
# copy image to SD card
# assume /dev/sdc is card
# parameter 1 - optional root device partition otherwise /dev/sdc

if [ '$1' == 'h' ]; then
   echo "Usage: $0 optional output device (like /dev/sdc)"
   exit 1
fi

if [ -z $2 ]; then
   SDCARD=/dev/sdc
else
   SDCARD=$2
fi

# make sure we don't wipe a drive
fs_uuid=$(blkid -o value -s UUID "${SDCARD}1")
echo $fs_uuid

if [ "$fs_uuid" == "bd15d195-c7ae-41ce-a452-2cbe78f69f09" ]; then
    echo "This is the Backup Drive"
    exit 1
fi

if [ "$fs_uuid" == "e8f5bf4f-d6c3-4c50-bcf7-fba0a276652c" ]; then
    echo "This is the Internal Files Drive"
    exit 1
fi

DEV_NAME="$(basename -- $SDCARD)"

echo $DEV_NAME

BOOTFS_PART_DEV="${SDCARD}1"
BOOTFS_PART_MNT=/mnt/boot

ROOTFS_PART_DEV="${SDCARD}2"
ROOTFS_PART_MNT=/mnt/sdcard

umount $BOOTFS_PART_DEV $ROOTFS_PART_DEV

mount $BOOTFS_PART_DEV $BOOTFS_PART_MNT
mount $ROOTFS_PART_DEV $ROOTFS_PART_MNT

echo $BOOTFS_PART_DEV
echo $BOOTFS_PART_MNT
echo $ROOTFS_PART_DEV
echo $ROOTFS_PART_MNT

df
echo "WARNING writing to $SDCARD"
echo "Are you sure? "
read -p "Press y to continue or any other key to stop. " -n 1 -r
echo    # (optional) move to a new line

if [[ $REPLY =~ ^[Yy]$ ]]
then
    echo "writing to $SDCARD root dir"
    cp rpi-setup/setup $ROOTFS_PART_MNT/root
    cp /opt/iiab/iiab-factory/box/generic/merge_local_vars.py $ROOTFS_PART_MNT/root
    chmod +x $ROOTFS_PART_MNT/root/setup

    echo "export LS_OPTIONS='--color=auto'" >>$ROOTFS_PART_MNT/root/.bashrc
    echo "alias ll='ls \$LS_OPTIONS -lav'" >>$ROOTFS_PART_MNT/root/.bashrc

    pushd $ROOTFS_PART_MNT/root
    mkdir -p .ssh
    cd .ssh

    cp /root/.ssh/authorized_keys_20130304 authorized_keys
    cd ..

    chmod 700 ~/.ssh
    chmod 600 ~/.ssh/authorized_keys

    popd

    touch $BOOTFS_PART_MNT/ssh
    # cp touch userconf.txt $BOOTFS_PART_MNT/ must be copy/paste error
    cp userconf.txt $BOOTFS_PART_MNT/
    df
    umount $BOOTFS_PART_MNT
    umount $ROOTFS_PART_MNT
fi
